{% set python_min = "3.11" %}
{% set name = "catalystcoop.ferc_xbrl_extractor" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/catalystcoop_ferc_xbrl_extractor-{{ version }}.tar.gz
  sha256: 4af312476eb7d4188fbef43c2c18d892db09e6b27f4aef5bff072516ed0ce871

build:
  entry_points:
    - xbrl_extract = ferc_xbrl_extractor.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }},<3.14
    - arelle-release >=2.32,<3
    - coloredlogs >=14.0,<15.1
    - python-duckdb >=1.3.2
    - frictionless >=5,<6
    - lxml >=4.9.1,<7
    - numpy >=1.16,<3
    - pandas >=1.5,<3
    - pyarrow >=14.0.1
    - pydantic >=2,<3
    - sqlalchemy >=1.4,<3
    - stringcase >=1.2,<2

test:
  imports:
    - ferc_xbrl_extractor
  commands:
    - pip check
    - xbrl_extract --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/catalyst-cooperative/ferc-xbrl-extractor
  summary: A tool for extracting data from FERC XBRL regulatory filings into SQLite databases.
  dev_url: https://github.com/catalyst-cooperative/ferc-xbrl-extractor
  doc_url: https://catalystcoop-ferc-xbrl-extractor.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - zschira
    - zaneselvans
    - jdangerx
